-- Custom SQL migration file, put your code below! --
-- TASK-RLS-005: protect tenant-owned leads, chat sessions, and messages.
-- Ordinary authenticated requests receive only the least-privilege columns
-- needed for the current application paths. Trusted server-side roles retain
-- the future path for derived fields and assistant/system messages.

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;--> statement-breakpoint

-- Leads: members may read and create rows only inside their own business.
-- Updates are limited to ordinary lead fields. There is intentionally no
-- authenticated DELETE policy.
REVOKE ALL PRIVILEGES
  ON TABLE public.leads
  FROM PUBLIC, anon, authenticated;--> statement-breakpoint
GRANT SELECT
  ON TABLE public.leads
  TO authenticated;--> statement-breakpoint
GRANT INSERT (
  business_id,
  name,
  email,
  company,
  role,
  company_size,
  use_case,
  budget,
  timeline,
  product_interest,
  buying_intent,
  qualification_status
)
  ON TABLE public.leads
  TO authenticated;--> statement-breakpoint
GRANT UPDATE (
  name,
  email,
  company,
  role,
  company_size,
  use_case,
  budget,
  timeline,
  product_interest,
  buying_intent,
  qualification_status,
  updated_at
)
  ON TABLE public.leads
  TO authenticated;--> statement-breakpoint

CREATE POLICY leads_select_members
  ON public.leads
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (private.is_business_member(business_id));--> statement-breakpoint

CREATE POLICY leads_insert_members
  ON public.leads
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (private.is_business_member(business_id));--> statement-breakpoint

CREATE POLICY leads_update_members
  ON public.leads
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (private.is_business_member(business_id))
  WITH CHECK (private.is_business_member(business_id));--> statement-breakpoint

-- Sessions: authenticated members may read and create sessions in their own
-- business. visitor_id is generated by the database and is not writable by
-- ordinary clients. The composite lead relationship remains enforced by the
-- existing foreign key.
REVOKE ALL PRIVILEGES
  ON TABLE public.chat_sessions
  FROM PUBLIC, anon, authenticated;--> statement-breakpoint
GRANT SELECT
  ON TABLE public.chat_sessions
  TO authenticated;--> statement-breakpoint
GRANT INSERT (
  business_id,
  lead_id,
  status,
  expires_at
)
  ON TABLE public.chat_sessions
  TO authenticated;--> statement-breakpoint
GRANT UPDATE (
  lead_id,
  status,
  updated_at
)
  ON TABLE public.chat_sessions
  TO authenticated;--> statement-breakpoint

CREATE POLICY chat_sessions_select_members
  ON public.chat_sessions
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (private.is_business_member(business_id));--> statement-breakpoint

CREATE POLICY chat_sessions_insert_members
  ON public.chat_sessions
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (private.is_business_member(business_id));--> statement-breakpoint

CREATE POLICY chat_sessions_update_members
  ON public.chat_sessions
  AS PERMISSIVE
  FOR UPDATE
  TO authenticated
  USING (private.is_business_member(business_id))
  WITH CHECK (private.is_business_member(business_id));--> statement-breakpoint

-- Messages are append-oriented. Ordinary authenticated clients may insert
-- only user messages with server-defaulted operational metadata. There are no
-- UPDATE or DELETE policies. The composite session relationship prevents a
-- message from combining one business_id with another business's session.
REVOKE ALL PRIVILEGES
  ON TABLE public.messages
  FROM PUBLIC, anon, authenticated;--> statement-breakpoint
GRANT SELECT
  ON TABLE public.messages
  TO authenticated;--> statement-breakpoint
GRANT INSERT (
  business_id,
  session_id,
  role,
  content
)
  ON TABLE public.messages
  TO authenticated;--> statement-breakpoint

CREATE POLICY messages_select_members
  ON public.messages
  AS PERMISSIVE
  FOR SELECT
  TO authenticated
  USING (private.is_business_member(business_id));--> statement-breakpoint

CREATE POLICY messages_insert_users
  ON public.messages
  AS PERMISSIVE
  FOR INSERT
  TO authenticated
  WITH CHECK (
    private.is_business_member(business_id)
    AND role = 'user'::public.message_role
  );
